name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    - name: Install Dependencies
      run: cargo fetch

    - name: Build Executable
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: target/x86_64-pc-windows-msvc/release/m2psp.exe
